name: Continuous Deployment

on: push

jobs:
  continuous-deployment:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Using Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 22.
          cache: "npm"
          cache-dependency-path:~//.npm

      - name: Build the project and install dependencies and run tests
        run: |
          npm install
          npm run build
          npm test

